### ISSUE TITLE
Immobiliser - chec for the dat

### ISSUE THREAD

**Issue by tombartosz** [gaucho1978/BACCAble#1]
Hi, I found out this project and also found out your message:
https://www.giuliaforums.com/threads/how-to-anti-theft-can-bus-device.63034/

“…Basically any diagnostic session with the RFHUB or other control module starts with the 10 03 command sent to the address of the module, the RFHUB has the address 0xC7. So the command looks like 18 DA C7 F1 02 10 03 . Your tool can monitor the bus for the command and start sending 18 DA C7 F1 02 11 01 – the reset module command. The expected reply from the RFH would be 18 DA F1 C7 01 51 , so your tool can monitor the bus for the reply and immediately send another reset command. This most probably will result in AlfaOBD not able to proceed.”

I can not find in code, where you check that 10 03 command. 
I found only this line (main.c:197) :
if ((rx_msg_header.ExtId==0x18DAC7F1) ||( (rx_msg_header.ExtId==0x18DAF1C7) && (floodTheBusStartTime==0)) ){   

I belive, you start panic alarm if received message to RFHub (0x18DAC7F1) or from RFHub (0x18DAF1C7) . 
Is it not making false alarms when other modules communicates to and from RFHub ?

**Comment by gaucho1978** [comment]
Hi. Thank you for the question. I found that no one connects to rfhub, therefore the solution works fine. I'm using it since 3 months. Everything starts from the fact that i decided to power BACCABLE by usb, in order to avoid to drain battery. The usb is on when you enter the car and when the thief connects to rfhub. This means that I will miss the first thief message, but I'm for sure able to intercept the reply from the rfhub.

**Comment by tombartosz** [comment]
Can you share me your email?
